### PR TITLE
attempt to fix USA checkout form

### PR DESCRIPTION
**Pull request by adrichman**
attempt to fix USA checkout form (unknown what fields will be called on drop day)
this incorporates the fixes mentioned in these issues:
https://github.com/carl1to/Cop-It-Supreme-Bot/issues/1
https://github.com/carl1to/Cop-It-Supreme-Bot/issues/102

### CODE REVIEW

**Comment by shaggy2dabs** [comment]
Thank you and yeah the Key Word Finder didn't work on drop that either it went to the proper pages but it didn't find the items by keyword and again the autofill didn't work so if those issues are fixed everything else is working fine

**Comment by adrichman** [comment]
I successfully completed a purchase with this version, but that is today (not on drop day). However I had to:
- disable hiding the captcha
- disable auto-checkout
Without doing these, my credit card was denied

**Comment by shaggy2dabs** [comment]
I never use those LOL

**Comment by shaggy2dabs** [comment]
But to get these updates what do I have to do do I just have to re-download the bot cuz in all honesty I don't really know what to do like can I edit shit in Notepad before I add it to Chrome LOL

**Comment by adrichman** [comment]
you can download the re-built extension from my changes on my fork:
https://github.com/adrichman/Cop-It-Supreme-Bot/raw/master/bin/CopIt.crx

**Comment by apates5** [comment]
Wait so I can't use this bot becuase I'm at school and I use this bot to auto checkout and bypass recaptcha. So u can't use this anymore?

**Comment by adrichman** [comment]
i haven’t had success with those settings unfortunately but it may work for
you. this is obviously not able to be tested.

**Comment by apates5** [comment]
Oh ok do you know any other free bots that have these setting that work? Or even a cheap bot that works well?

**Comment by adrichman** [comment]
FWIW, I just successfully placed an order automatically. I had to disable "Remove reCaptcha on checkout page". This captcha does NOT require you to do ANYTHING. 
Leave the option disabled and keep the "Auto submit checkout page" option enabled. This just worked for me. On drop day YMMV.

**Comment by apates5** [comment]
Does anyone know another free supreme bot?

**Comment by marijnbr** [comment]
Why can i only choose creditcard as payment method, i'd like to pay with paypal!

**Comment by shaggy2dabs** [comment]
@marjnbr bro if you're going to try to pay with PayPal you're taking an L no matter what LOL

**Comment by apates5** [comment]
Does anyone know another free supreme bot?

**Comment by marijnbr** [comment]
@shaggy2dabs unfortunately it's my only option if i want to buy from supreme

**Comment by apates5** [comment]
Can someone add a manual captcha harvester or even better a automatic harvester? That would make this bot AMAZING! Thanks for anybody who tries to do it!

**Comment by apates5** [comment]
the autofill doesnt work anymore. it puts in the the address and name and everything, but it doesnt put in the card number and cvc. Someone help please!

**Comment by adrichman** [comment]
@apates are you saying that you pulled in the changes in this pull request and they failed to work?

**Pull request merged**
